# Generated by Django 6.0.5 on 2026-06-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Presentacion', '0002_alter_categoria_options_alter_certificacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciatrabajo',
            name='tecnologias',
        ),
        migrations.RemoveField(
            model_name='experienciatrabajo',
            name='trabajo_actual',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='destacado',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='herramientas',
        ),
    ]
