# Generated by Django 6.0.5 on 2026-06-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentacion', '0003_remove_experienciatrabajo_tecnologias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
